# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0c002dc
_src_path: gh:scipp/copier_template
description: Reflectometry data reduction for the European Spallation Source
github_linux_image: ubuntu-20.04
max_python: '3.11'
min_python: '3.8'
orgname: scipp
projectname: essreflectometry
year: 2023
